### ISSUE TITLE
httpcore required for PUT response to CloudFormation

### ISSUE THREAD

**Issue by timmattison** [SunRun/cfn-response-java#5]
When using this library with a minimal example I get the following exception in my CloudWatch Logs:

```
org/apache/http/ssl/SSLContexts: java.lang.NoClassDefFoundError java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts at
org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966) at
com.sunrun.cfnresponse.CfnResponseSender.<init>(CfnResponseSender.java:32)
```

Adding this dependency to my pom.xml fixed the issue:

``` xml
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpcore</artifactId>
  <version>4.4.4</version>
</dependency>
```

**Comment by jhovell** [comment]
@timmattison I think there might be a version mismatch between some other httpcore and httpclient JARs on your classpath. It seems org/apache/http/ssl/SSLContexts moved packages between 4.3 and 4.4. Are you sure you don't have another dependency in your POM that is resolving httpclient to a different version?

Here is the dependency hierarchy for cfn-response-java as calculated by Eclipse... httpcore 4.4.4 should already be on the classpath.

<img width="514" alt="screen shot 2016-05-03 at 8 38 05 am" src="https://cloud.githubusercontent.com/assets/1376570/14989506/102d76be-110d-11e6-9ec2-b553e57d5654.png">

I'd like to figure out what is causing this issue, since adding this dependency to the POM should not be necessary.

**Comment by jhovell** [comment]
@timmattison sounds like this is a conflict with aws-java-sdk-core in your POM due to the way aws-java-sdk declares a dependency on httpclient and httpcore explicitly. 

I would recommend either including the below snippet inside the ```<dependency>``` block for aws-java-sdk-core or adding the extra httpcore dependency yourself to elsewhere in your POM as it sounds like you have done. If I were you I would prefer the exclude method since then you don't need to track any minor updates to httpclient if cfn-response-java updates to a later version or another library does the same. 4.3.6 is 1.5 years old at this point so likely other libraries may provide a newer version...

```xml 
      <exclusions>
        <exclusion>
          <artifactId>httpclient</artifactId>
          <groupId>org.apache.httpcomponents</groupId>
        </exclusion>
        <exclusion>
          <artifactId>httpcore</artifactId>
          <groupId>org.apache.httpcomponents</groupId>
        </exclusion>
      </exclusions>
```

**Comment by jhovell** [comment]
For clarity to explain what is going on when aws-java-sdk-core 1.10.74 is included in the same project:

![screen shot 2016-05-03 at 11 10 21 am](https://cloud.githubusercontent.com/assets/1376570/15001019/f457794e-1148-11e6-9f31-5c3d1d68edf3.png)

**Comment by jhovell** [comment]
@timmattison sounds like this can be worked around by excluding httpcore from your aws-java-sdk-core dependency. Also it looks like AWS may update their POM in a future release of aws-java-sdk.

I'll close this issue, but re-open it if you feel there is some further action needed on my part.
